# Generated by Django 2.0.8 on 2018-09-28 08:53

from django.db import migrations
import django_enumfield.db.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=django_enumfield.db.fields.EnumField(default=2, enum=users.models.UserTypeEnum),
        ),
    ]
