# Generated by Django 2.0.8 on 2018-10-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180928_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
