# Generated by Django 2.0.8 on 2018-10-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, default='static/icons/shop.png', upload_to='shop'),
        ),
    ]
