# Generated by Django 2.0.8 on 2018-10-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, default='<eCommerce>/static/icons/shop.png', upload_to='shop'),
        ),
    ]
